[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
uptodown-dlurl = "https://photomath.en.uptodown.com/android"
dpi = "120-640dpi"

[SolidExplorer]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
version = "beta"

[Instagram]
#apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
included-patches = "'Hide ads' 'Open links externally' 'Sanitize sharing links' 'Disable signature check'"
exclusive-patches = true

[Tiktok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[GoogleNews]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
