[YouTube]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"

[GooglePhotos]
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
arch = "arm64-v8a"

[SolidExplorer]
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-beta"
arch = "arm64-v8a"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Open links externally' 'Sanitize sharing links' 'Disable signature check'"
exclusive-patches = true

[Tiktok]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"

[GoogleNews]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
arch = "arm64-v8a"
